spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://10.1.1.106:3306/AI_BUS?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 10.1.1.207
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
docker_host: tcp://10.1.1.205:7788/
myserver:
  user: root
  password: 660077

docker:
  kafkaserviceimage:
    name: kafkaservice
    label: 1.0
  watchserviceimage:
    name: watchservice
    label: 1.0
  redis:
    name: redis
    label: 3.0.6
  modelserviceimage:
    name: busmodelservice
    label: 1.1



watchservicecmd:
  bash /opt/redis-6.2.7/deps/hiredis/send_to_redis/watch.sh
aiservicecmd:
  bash /root/Bus_Group/Bus_peopleEst_s2_v4-Copy/bus.sh



