spring:
  datasource:
    password: database@lab607
    username: root
    url: jdbc:mysql://124.220.223.62:6106/AI_BUS?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 9763
    host: 159.27.184.52
    password: Zhangzhengxu123.
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
docker_host: tcp://124.220.223.62:7788/
#myserver:
#  user: root
#  password: 660077

docker:
  kafkaserviceimage:
    name: kafkaservice
    label: 1.1
  watchserviceimage:
    name: watchservice
    label: 1.0
  redis:
    name: redis
    label: 3.0.6
  busmodelserviceimage:
    name: busmodelservice
    label: 1.1
  stationmodelserviceimage:
    name: stationmodelservice
    label: 1.0



#watchservicecmd:
#  bash /opt/redis-6.2.7/deps/hiredis/send_to_redis/watch.sh
#aiservicecmd:
#  bash /root/Bus_Group/Bus_peopleEst_s2_v4-Copy/bus.sh



